HUGGINGFACE_API_TOKEN = ""
OPENAI_API_TOKEN = ""
#LLM_MODEL = "gpt-3.5-turbo-0125"
#RELATIONSHIPS_LLM_MODEL = "gemini-2.0-flash"
RAG_LLM_MODEL = "gemini-2.5-flash-lite-preview-06-17"
#RAG_LLM_MODEL = ""gemini-1.5-flash"
#RAG_LLM_MODEL = "gemini-2.5-flash"
#RAGAS_LLM_MODEL= "gemini-2.0-flash"
RAGAS_LLM_MODEL= "gemini-2.5-flash-lite-preview-06-17"

GEMINI_API_TOKEN=""
# Wait 60 seconds before connecting using these details, or login to https://console.neo4j.io to validate the Aura Instance is available
NEO4J_URI=""
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD=""
AURA_INSTANCEID=""
AURA_INSTANCENAME="Free instance"